name: ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# dependabot triggered actions have more limited `GITHUB_TOKEN` permissions by default
# - see: https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions#changing-github_token-permissions
permissions:
  packages: write
  deployments: write
  pull-requests: write
  statuses: write
  checks: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: setup .net
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: restore
        run: dotnet restore

      - name: build
        run: dotnet build -c Release --no-restore

      - name: stage packages
        run: find . -name "Aoraki.Events.*.nupkg" -exec mv '{}' . \;

      - name: archive packages
        uses: actions/upload-artifact@v3
        with:
          name: packages
          path: "*.nupkg"
          if-no-files-found: error

  publish:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    needs:
      - build

    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3

      - name: setup .net
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: setup nuget
        run: dotnet nuget add source --name github "https://nuget.pkg.github.com/crookm/index.json"

      - name: publish packages
        run: dotnet nuget push "packages/*.nupkg" --api-key ${{ secrets.GITHUB_TOKEN }} --source "github" --skip-duplicate
